title: Eleme Mobilists
subtitle: null
description: null
author: null
language: zh-Hans
timezone: Asia/Shanghai
url: 'http://mobilists.eleme.io'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: null
category_generator:
  per_page: 10
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
theme: next
deploy:
  type: git
  repo: 'git@github.com:eleme/mobilists.git'
  branch: gh-pages
multiauthor:
  default_avatar: ''
  authors:
    - axl411:
        displayname: axl411
        avatar: 'https://avatars0.githubusercontent.com/u/5897680?v=3&s=400'
    - canaan:
        displayname: jianan.ye
    - JackCho:
        displayname: amigo
    - zhungxd:
        displayname: xiaodong.zhang
    - PhilCai:
        displayname: zheren.cai
        avatar: 'https://avatars0.githubusercontent.com/u/6828315?v=3&s=400'
    - stephenwzl:
        displayname: stephenwzl
        avatar: 'https://avatars3.githubusercontent.com/u/10472240?v=3&s=460'
    - BryanOne:
        displayname: BryanOne
        avatar: 'https://avatars1.githubusercontent.com/u/1538965?v=3&s=460'
friendlink:
  - name: LPD-iOS
    avatar: 'http://lrd.ele.me/images/ico.png'
    url: 'https://lpd-ios.github.io'
    introduction: '饿了么物流 iOS 开发组(LPD-iOS)'
  - name: stephenwzl
    avatar: 'https://ws1.sinaimg.cn/large/8696f529gy1feu8hi9100j209c08saeg.jpg'
    url: 'https://stephenw.cc'
    introduction: 'eleme mobile hexo theme 维修工'
